/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAuthenticatorAppDialog: typeof import('./resources/ts/components/dialogs/AddAuthenticatorAppDialog.vue')['default']
    AddEditAddressDialog: typeof import('./resources/ts/components/dialogs/AddEditAddressDialog.vue')['default']
    AddEditPermissionDialog: typeof import('./resources/ts/components/dialogs/AddEditPermissionDialog.vue')['default']
    AddEditRoleDialog: typeof import('./resources/ts/components/dialogs/AddEditRoleDialog.vue')['default']
    AddPaymentMethodDialog: typeof import('./resources/ts/components/dialogs/AddPaymentMethodDialog.vue')['default']
    AppBarSearch: typeof import('./resources/ts/@core/components/AppBarSearch.vue')['default']
    AppDateTimePicker: typeof import('./resources/ts/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/ts/@core/components/AppDrawerHeaderSection.vue')['default']
    AppLoadingIndicator: typeof import('./resources/ts/components/AppLoadingIndicator.vue')['default']
    AppPricing: typeof import('./resources/ts/components/AppPricing.vue')['default']
    AppSearchHeader: typeof import('./resources/ts/components/AppSearchHeader.vue')['default']
    AppStepper: typeof import('./resources/ts/@core/components/AppStepper.vue')['default']
    CardAddEditDialog: typeof import('./resources/ts/components/dialogs/CardAddEditDialog.vue')['default']
    ConfirmDialog: typeof import('./resources/ts/components/dialogs/ConfirmDialog.vue')['default']
    CreateAppDialog: typeof import('./resources/ts/components/dialogs/CreateAppDialog.vue')['default']
    CustomizerSection: typeof import('./resources/ts/@core/components/CustomizerSection.vue')['default']
    DialogCloseBtn: typeof import('./resources/ts/@core/components/DialogCloseBtn.vue')['default']
    EnableOneTimePasswordDialog: typeof import('./resources/ts/components/dialogs/EnableOneTimePasswordDialog.vue')['default']
    ErrorHeader: typeof import('./resources/ts/components/ErrorHeader.vue')['default']
    I18n: typeof import('./resources/ts/@core/components/I18n.vue')['default']
    Notifications: typeof import('./resources/ts/@core/components/Notifications.vue')['default']
    PaymentProvidersDialog: typeof import('./resources/ts/components/dialogs/PaymentProvidersDialog.vue')['default']
    PricingPlanDialog: typeof import('./resources/ts/components/dialogs/PricingPlanDialog.vue')['default']
    ReferAndEarnDialog: typeof import('./resources/ts/components/dialogs/ReferAndEarnDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./resources/ts/@core/components/ScrollToTop.vue')['default']
    ShareProjectDialog: typeof import('./resources/ts/components/dialogs/ShareProjectDialog.vue')['default']
    Shortcuts: typeof import('./resources/ts/@core/components/Shortcuts.vue')['default']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    TimelineBasic: typeof import('./resources/ts/views/demos/components/timeline/TimelineBasic.vue')['default']
    TimelineOutlined: typeof import('./resources/ts/views/demos/components/timeline/TimelineOutlined.vue')['default']
    TimelineWithIcons: typeof import('./resources/ts/views/demos/components/timeline/TimelineWithIcons.vue')['default']
    TwoFactorAuthDialog: typeof import('./resources/ts/components/dialogs/TwoFactorAuthDialog.vue')['default']
    UserInfoEditDialog: typeof import('./resources/ts/components/dialogs/UserInfoEditDialog.vue')['default']
    UserUpgradePlanDialog: typeof import('./resources/ts/components/dialogs/UserUpgradePlanDialog.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
